### ISSUE TITLE
dpctl: error during transaction.

### ISSUE THREAD

**Issue by AbdullahAlshraa** [OpenState-SDN/spider#2]
Dears,

I am working on the same area (Fault management) based on SPIDER.
I use the same method to send ping packets from source to destination. but sometimes, I see crash forwarding tables ! and the " dpctl: error during transaction" appears as an error message.

for instance, when I use Norway topology to send ping from switch number 1 to 22 through 20 (1 -> 20 ->22)
 I can see this inside 22 host, however this reply dose not reach to the source switch !!!

![dptclerror](https://user-images.githubusercontent.com/26813849/29036269-0baf0bc2-7b9f-11e7-91d1-a63a2c79633a.JPG)

I had checked out the reverse path or the path from switch number 22  to 1 through 21. and I found its table destroyed, thus the packet did not reach.
the second picture before the ping packet reached host 22

![capture](https://user-images.githubusercontent.com/26813849/29036832-577620b6-7ba1-11e7-897e-dcdba8b779c5.JPG)

the thired after the ping packet reached host 22 which the first picture appears that switch reply but the ping packet has been dropped because of the crashed forwarding table . 

![screen](https://user-images.githubusercontent.com/26813849/29036847-69ac80a4-7ba1-11e7-9267-32ae52d485ab.JPG)

I have read some thing about this error here https://github.com/CPqD/ofsoftswitch13/issues/15
,  but I did not understand  or I do not know if it is the same states.

I look forward to hearing you
thanks in advance

**Comment by AbdullahAlshraa** [comment]
At almost all of paths, there is no problem when sending ping packets in normal conditions
![capture](https://user-images.githubusercontent.com/26813849/29770493-aeecb0ae-8bef-11e7-83cb-f42f4b0d9d5b.JPG)

However, I modified the set link down button to change the link status between up and down every 10 seconds as the follow 

```
def set_link_down(self,node1,node2, faults,fault,fault_ID):
        if(node1 > node2):
            node1,node2 = node2,node1
       
        X =int(input('Please enter the number of rounds: '))
        for i in range(X):
            os.system('sudo ifconfig s'+str(node1)+'-eth'+str(self.ports_dict['s'+str(node1)]['s'+str(node2)])+' down')
            os.system('sudo ifconfig s'+str(node2)+'-eth'+str(self.ports_dict['s'+str(node2)]['s'+str(node1)])+' down')
            print "link between",str(node1), "and",str(node2),"is down"
            print (time.strftime("%I:%M:%S"))
            time.sleep(10)
            os.system('sudo ifconfig s'+str(node1)+'-eth'+str(self.ports_dict['s'+str(node1)]['s'+str(node2)])+' up')
            os.system('sudo ifconfig s'+str(node2)+'-eth'+str(self.ports_dict['s'+str(node2)]['s'+str(node1)])+' up')
            print "link between",str(node1), "and",str(node2),"is UP"
            print (time.strftime("%I:%M:%S"))
            time.sleep(10)
        print ' your experiment finished '
        print (time.strftime("%I:%M:%S"))
```
At the beginning, there were no problems in the normal or failure situation till around 100 ping packets.
![capture1](https://user-images.githubusercontent.com/26813849/29770968-cb25b84a-8bf1-11e7-9c68-ff7350c40a42.JPG)


Unfortunately, the crash forwarding tables problem  appeared again.

any advice will be appreciated

**Comment by DavideSanvito** [comment]
Hi Abdullah,
have you tried to check the log of the crashed switch after the crash?
It should be located in the /tmp/ folder and, if ofdatapath has been run with the max level of verbosity, you should get a hint about the possible problem. Can you check it?
Best,
Davide

**Comment by AbdullahAlshraa** [comment]
Hello,
I am not sure If I caught that well
I took the next Screenshot after the crashed Switch.
Could you tell me, which folder did you mean?

![capture](https://user-images.githubusercontent.com/26813849/29863849-259f1304-8d71-11e7-8d8f-340d8325a336.JPG)

However, I explained two different situations
The first one, Host 1 sent one Ping packet to host 22 in normal conditions (one packet is enough to make switch 22 crashed !!)

The second one, the crashed switch sent the same packet through all its ports repeatedly  (I think you meant this situation), so it perhaps run with the max level of verbosity

**Comment by DavideSanvito** [comment]
Hi,
try to look into the /tmp folder located in the root folder / of the file system.
Best,
Davide

**Comment by AbdullahAlshraa** [comment]
Thank you for your patience 
In regard to `the first situation` ( 1 to 22 )

 I found /tmp folder  in the root
![capture](https://user-images.githubusercontent.com/26813849/29916588-7c2107cc-8e3f-11e7-9480-712a1b82dbaa.JPG)

I used "gedit" to open s22-ofd.log        

![capture1](https://user-images.githubusercontent.com/26813849/29916738-fccd4de0-8e3f-11e7-8220-70fae168b206.JPG)
  
and I also used "gedit" to open s22-ofp.log 

![capture2](https://user-images.githubusercontent.com/26813849/29917316-e60a6474-8e41-11e7-9453-0e5eb251ef54.JPG)


you can find the whole file (s22-ofp.log ) here [txt.txt](https://github.com/OpenState-SDN/spider/files/1266574/txt.txt)
----------------------------------------------------------------------
----------------------------------------------------------------------
In regard to `the second situation.`

 I found /tmp folder  in the root
![capture3](https://user-images.githubusercontent.com/26813849/29918830-45319134-8e47-11e7-88ca-488b1b2b682f.JPG)

I used "gedit" to open s24-ofd.log    
![capture4](https://user-images.githubusercontent.com/26813849/29918848-58476d5c-8e47-11e7-8cdf-e573bc56d5b9.JPG)

you can find the whole file (s24-ofd.log ) here 
[123.txt](https://github.com/OpenState-SDN/spider/files/1266715/123.txt)

I also used "gedit" to open s24-ofp.log  

![capture5](https://user-images.githubusercontent.com/26813849/29918900-8eeaf180-8e47-11e7-8f99-87c7479ef22c.JPG)

 you can find the whole file (s24-ofp.log ) here 
[1234.txt](https://github.com/OpenState-SDN/spider/files/1266720/1234.txt)


Thanks in advance
Abdullah
